name: Update README when docs commit is pushed

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if there is a docs commit
        id: check_docs
        run: |
          echo "Checking commits for docs:"
          for i in $(seq 0 $(($(jq '.commits | length' "$GITHUB_EVENT_PATH") - 1))); do
            commit_message=$(jq -r ".commits[$i].message" "$GITHUB_EVENT_PATH")
            commit_id=$(jq -r ".commits[$i].id" "$GITHUB_EVENT_PATH")
            echo "Found commit: $commit_message"

            if [[ "$commit_message" == docs* ]]; then
              echo "docs commit detected."
              echo "found=true" >> $GITHUB_ENV
              echo "commit_message=$commit_message" >> $GITHUB_ENV
              echo "commit_id=$commit_id" >> $GITHUB_ENV
              break
            fi
          done

      - name: Update README if docs commit exists
        if: env.found == 'true'
        run: |
          echo "Updating README..."
          echo "- $(date '+%Y-%m-%d'): [${{ env.commit_message }}](https://github.com/${{ github.repository }}/commit/${{ env.commit_id }})" >> README.md

      - name: Commit and push README if updated
        if: env.found == 'true'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "📝 Update README from docs commit" || echo "No changes to commit"
          git push
